{"name": "test_create_user_invalid_token", "status": "broken", "statusDetails": {"message": "NameError: name 'requests' is not defined", "trace": "base_url = 'https://gorest.co.in', end_point = '/public/v2/users/'\n\n    @allure.feature(\"User Management\")\n    @allure.story(\"Negative Scenarios\")\n    @pytest.mark.negative\n    def test_create_user_invalid_token(base_url, end_point):\n        \"\"\"Verify creating a user with an invalid token fails (401)\"\"\"\n        data = {\"name\": \"invalid_user\", \"email\": \"invalid@user.com\", \"gender\": \"male\", \"status\": \"active\"}\n        bad_headers = {\"Authorization\": \"Bearer invalidtoken123\"}\n    \n>       post_response = requests.post(base_url + end_point, headers=bad_headers, json=data, timeout=10)\n                        ^^^^^^^^\nE       NameError: name 'requests' is not defined\n\ntests/test_users_negative.py:32: NameError"}, "description": "Verify creating a user with an invalid token fails (401)", "start": 1757600249518, "stop": 1757600249519, "uuid": "2768cf51-1f7e-475c-ac2f-ad502c463b96", "historyId": "835ce4bbef170a855e338b21bdd139df", "testCaseId": "835ce4bbef170a855e338b21bdd139df", "fullName": "tests.test_users_negative#test_create_user_invalid_token", "labels": [{"name": "story", "value": "Negative Scenarios"}, {"name": "feature", "value": "User Management"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users_negative"}, {"name": "host", "value": "riju-Inspiron-15-3515"}, {"name": "thread", "value": "733435-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users_negative"}], "titlePath": ["tests", "test_users_negative.py"]}